### ISSUE TITLE
CSS doing browsers job

### ISSUE THREAD

**Issue by farishkash** [Lhandle212/prj-rev-bwfs-dasmoto#1]
I understand learners looking at the source code to figure out how things are done.

The problem is what exactly what you are you suppose to use.

This is your css block below.  Starting with display:block do you know exactly what is going on?

```
h1 {
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
  font-size: 100px;
  color: khaki;
  text-align: center;
  display: block;
  -webkit-margin-before: 0.67em;
  -webkit-margin-after: 0.67em;
  -webkit-margin-start: 0px;
  -webkit-margin-end: 0px;
  font-weight: bold;
}
```

The problem is, this looks like you copied the user agent stylesheet.

So let me explain exactly what this is.

Whenever you put a html element, such as h2, paragraph, body, etc it has a set of built in default styles that the browser renders.

This code below is the default style so you never have to type it in the style sheet, just by using the h1 element this is automatic.

```
  display: block;
  -webkit-margin-before: 0.67em;
  -webkit-margin-after: 0.67em;
  -webkit-margin-start: 0px;
  -webkit-margin-end: 0px;
  font-weight: bold;
```

![das](https://user-images.githubusercontent.com/5844161/31751954-446f0620-b43d-11e7-8a55-0e6f3b34ef0f.jpg)

The user agent stylesheet means what style does the browser apply by default.

So you repeated what the browser was going to do regardless and there was no need to type this.

**Comment by Lhandle212** [comment]
Thank you for your clarification, that is helpful!  I will try to redo it without that part so that I can see that it will still behave the same way without putting that in there.  I could've swore that when I didn't have that in there it looked differently, but I would like to learn and improve.
