### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [Lhandle212/prj-rev-bwfs-dasmoto#2]
Needs improvement.

The site structure is fine, the css is a issue because of the user agent style sheet being used.

Nothing wrong with using Chrome dev tools to figure things out but unfortunately you used the wrong thing.  If aren't sure what to use or how to make this site work, you should reach out to the advisors, by week 5 the difficulty is going to ramp up.

Speaking of which so you can see what is coming up, go to flexboxfroggy.com and see how far you can get this will give you an idea of the css system that will be used in the later rpojects.

**Comment by Lhandle212** [comment]
Thank you for your comments!
I was trying to follow all the previous sections, but according to your comments I need improvement, just not sure what.   I have never done this before.  I guess I will need to go over the Chrome dev tools again to try and figure out where I went wrong.  I will check out the website you suggested and try to reach out to the advisors before week 5.
